name: Linode CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  access-linode:
    runs-on: ubuntu-latest

    steps:
      - name: Linode Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd medicina-servidor/
            git pull
            pm2 restart flemik-node
